### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by haribo-hm** [aojes/omnicat#1]

**Comment by haribo-hm** [comment]
Reduce size/spacing. Fit more into center screen space. Less scrolling.

**Comment by tidelake** [comment]
Pushed changes to the Dass form, now shows 2 questions at a time. Effects need work but it's okay. Thought that would be good practice for the harder Wellness form.

**Comment by tidelake** [comment]
scroll events are within reach for refinement as needed 
![wellness-noscroll](https://user-images.githubusercontent.com/12180/53478857-69906e80-3a3d-11e9-8b5e-a9d09cc67c64.gif)

**Comment by haribo-hm** [comment]
Nice work it's starting to look pretty tidy : )
